export const BUY_IEO_ITEM = 'buy/IEO_ITEM';
export const BUY_IEO_RESPONSE = 'buy/IEO_RESPONSE';
export const BUY_IEO_ERROR = 'buy/IEO_ERROR';
export const RESET_BUY_IEO_RESPONSE = 'buy/RESET_BUY_IEO_RESPONSE';

export const GET_TOTAL_IEO_BUYERS = 'buy/GET_TOTAL_IEO_BUYERS';
export const TOTAL_IEO_BUYERS_DATA = 'buy/TOTAL_IEO_BUYERS_DATA';
export const TOTAL_IEO_BUYERS_ERROR = 'buy/TOTAL_IEO_BUYERS_ERROR';
